name: Compilation_Test
on:
  push:
    branches:
      - 'main'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Download repo files
        uses: actions/checkout@v4.2.2
      - name: Compile files
        uses: xu-cheng/latex-action@v4
        with:
          working_directory: Template
          root_file: Template.tex
      - name: Upload compiled file
        uses: actions/upload-artifact@v4
        with: 
          name: My_buisness_hour_sign
          path: Template/Template.pdf
